# Generated by Django 6.0.5 on 2026-05-27 05:25

import core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledgers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('income', 'Income'), ('essential', 'Essential'), ('variable', 'Variable'), ('provision', 'Provision')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('CLP', 'CLP'), ('CLF', 'CLF'), ('USD', 'USD')], max_length=3)),
                ('frequency', models.CharField(choices=[('M', 'Monthly'), ('Q', 'Quarterly'), ('H', 'Half-yearly'), ('Y', 'Yearly'), ('CUSTOM', 'Custom')], max_length=6)),
                ('custom_months', core.fields.MonthListField(blank=True, null=True)),
                ('start_month', models.DateField()),
                ('total_installments', models.PositiveIntegerField(blank=True, null=True)),
                ('payoff_month', models.DateField(blank=True, null=True)),
                ('is_saving', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogItemRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from_month', models.DateField()),
                ('amount_real', models.DecimalField(decimal_places=4, max_digits=16)),
                ('payment_source', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card')], max_length=11)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.catalogitem')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['effective_from_month'],
                'constraints': [models.UniqueConstraint(fields=('catalog_item', 'effective_from_month'), name='unique_revision_per_month')],
            },
        ),
    ]
